title: Ahmed Portfolio
description: My Personal Blog & Portfolio

url: "https://yourusername.github.io"
baseurl: ""

remote_theme: pages-themes/contrast@v1.0.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed

permalink: /:title/

nav:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: My Journey
    link: /journey
  - name: Blog
    link: /blog
